version: '3.5'
services:
    catalog:
      image: rafafontana/simpleplatform_catalog:latest
      container_name: platform_catalog
      expose:
        - "80"
      ports: 
        - "8080:80"
    sensor:
      image: rafafontana/simpleplatform_sensor:latest
      container_name: platform_sensor
      expose:
        - "80"
      ports: 
        - "9080-9090:80"
      depends_on: 
        - catalog
        - thingspeak_adaptor
      links:
        - catalog
    devicemonitor:
      image: rafafontana/simpleplatform_devicemonitor:latest
      container_name: platform_devicemonitor
      depends_on: 
        - catalog    
      links:
        - catalog
    
    thingspeak_adaptor:
      build: ./thingspeak_adaptor
      depends_on: 
        - catalog    
      links:
        - catalog

version: '3.5'
services:
    catalog:
      build: ./catalog
      expose:
        - "80"
      ports: 
        - "8080:80"
    sensor:
      build: ./sensor
      expose:
        - "80"
      ports: 
        - "9080-9090:80"
      depends_on: 
        - catalog
        - thingspeak_adaptor   
      links:
        - catalog
    devicemonitor:
      build: ./devicemonitor
      depends_on: 
        - catalog    
      links:
        - catalog
    
    thingspeak_adaptor:
      build: ./thingspeak_adaptor
      depends_on: 
        - catalog    
      links:
        - catalog

